version: '3'

services:
  bdd:
    image: postgres:11
    env_file:
      - bdd.env
    volumes:
      - cash_data:/var/lib/postgresql/data
    restart: unless-stopped

  maven:
    build:
      context: .
      dockerfile: docker-maven/Dockerfile
    volumes:
      - mvn_cache:/root/.m2
      - jar_dir:/dist

  back:
    build:
      context: docker-java
    env_file:
      - bdd.env
    volumes:
      - jar_dir:/dist
    ports:
      - "8080:8080"
      - "8081:8080"

  #gradle:
    #build:
      #context: ../Cash_Manager_Front
    #volumes:
      #- ../Cash_Manager_Front/:/app

volumes:
  cash_data:
  mvn_cache:
  jar_dir:
